
import { Translations } from './types';

export const TRANSLATIONS: Record<'da' | 'en', Translations> = {
  da: {
    title: 'Blodsukker Log',
    dashboard: 'Dashboard',
    logs: 'Log historik',
    assistant: 'AI Assistent',
    settings: 'Indstillinger',
    addEntry: 'Ny måling',
    valueLabel: 'Værdi (mmol/L)',
    timestampLabel: 'Tidspunkt',
    noteLabel: 'Note (valgfri)',
    save: 'Gem måling',
    cancel: 'Annuller',
    delete: 'Slet',
    exportData: 'Eksportér data (JSON)',
    importData: 'Importér data (JSON)',
    average: 'Gennemsnit',
    highest: 'Højeste',
    lowest: 'Laveste',
    last14Days: 'Sidste 14 dage',
    lastMonth: 'Sidste måned',
    last3Months: 'Sidste 3 måneder',
    noData: 'Ingen data at vise endnu.',
    aiPrompt: 'Spørg din assistent om dine målinger...',
    aiPlaceholder: 'Hvordan ser mit blodsukker ud i dag?',
    languageToggle: 'Skift til Engelsk',
    confirmDelete: 'Er du sikker på du vil slette denne måling?',
    units: 'mmol/L'
  },
  en: {
    title: 'Blood Sugar Log',
    dashboard: 'Dashboard',
    logs: 'Log History',
    assistant: 'AI Assistant',
    settings: 'Settings',
    addEntry: 'New Entry',
    valueLabel: 'Value (mmol/L)',
    timestampLabel: 'Timestamp',
    noteLabel: 'Note (optional)',
    save: 'Save Entry',
    cancel: 'Cancel',
    delete: 'Delete',
    exportData: 'Export Data (JSON)',
    importData: 'Import Data (JSON)',
    average: 'Average',
    highest: 'Highest',
    lowest: 'Lowest',
    last14Days: 'Last 14 Days',
    lastMonth: 'Last Month',
    last3Months: 'Last 3 Months',
    noData: 'No data to show yet.',
    aiPrompt: 'Ask your assistant about your logs...',
    aiPlaceholder: 'How does my blood sugar look today?',
    languageToggle: 'Switch to Danish',
    confirmDelete: 'Are you sure you want to delete this entry?',
    units: 'mmol/L'
  }
};
